global:
  scrape_interval: 15s

scrape_configs:
  - job_name: 'scorevision-validator'
    static_configs:
      - targets: ['validator:8110']
        labels:
          instance: validator

  - job_name: 'scorevision-runner'
    static_configs:
      - targets: ['runner:8000']
        labels:
          instance: runner
